### ISSUE TITLE
Error tokenizing card

### ISSUE THREAD

**Issue by MarceloPetrucio** [jlcd/api-cielo30-laravel#1]
Error tokenizing card, TokenizeCardRequest class is extending AbstractSaleRequest and this has changed to AbstractRequest.

[TokenizeCardRequest.zip](https://github.com/jlcd/api-cielo30-laravel/files/3458313/TokenizeCardRequest.zip)

**Comment by jlcd** [comment]
@MarceloPetrucio com o MR do outro repositorio, resolve isso aqui também, certo?
