### ISSUE TITLE
Questão: Como integrar com Laravel Cashier

### ISSUE THREAD

**Issue by timoteo7** [jlcd/api-cielo30-laravel#4]
Olá

como o Laravel tem o [Cashier](https://github.com/laravel/cashier) que faz integração com o Stripe (e também [Mollie](https://github.com/laravel/cashier-mollie) ou [Braintree](https://github.com/laravel/cashier-braintree))
Você saberia de alguma [documentação](https://laravel.com/docs/7.x/billing) de como integrar ou fazer a compatibilidade com um adquirente novo, como a Cielo ?

**Comment by jlcd** [comment]
Rapaz infelizmente não sei dizer.
